# Generated by Django 3.1.1 on 2020-10-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstats',
            name='card',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='value',
        ),
        migrations.AddField(
            model_name='account',
            name='cards',
            field=models.ManyToManyField(to='qrCards.Card'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardStats',
            field=models.ManyToManyField(to='qrCards.CardStats'),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='value',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountCards',
        ),
    ]
